# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_title',
            name='text',
            field=models.CharField(default='Dropshadow', max_length=200),
        ),
    ]
