# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170213_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Title',
            new_name='BlogTitle',
        ),
    ]
